{% set name = "django-guid" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_guid-{{ version }}.tar.gz
  sha256: 242fdfaf49bf0ba12ebc2d3e289f22a5ff8e0390824483957462de72540d3dff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - django >=3.2,<6

test:
  imports:
    - django_guid
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/snok/django-guid
  summary: Middleware that enables single request-response cycle tracing by injecting a unique ID into project logs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://django-guid.readthedocs.io/en/latest
  dev_url: https://github.com/snok/django-guid

extra:
  recipe-maintainers:
    - sumanth-manchala
